variables:
  - group: "calms-general"
  - name: "vmImageName"
    value: "ubuntu-20.04"
  - name: "tag"
    value: $(Build.BuildId)
  - name: "websitePath"
    value: "services/calms-website"
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: isDevelop
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

pr:
  autoCancel: true
  drafts: false

trigger:
  branches:
    include:
      - develop
      - master
  paths:
    include:
      - src
      - deployment

pool:
  vmImage: $(vmImageName)

stages:
  - stage: CI
    displayName: CI Stage
    jobs:
      - job: Build_website
        displayName: Build website
        steps:
          - task: Cache@2
            inputs:
              key: "npm | “$(Agent.OS)” | $(Build.SourcesDirectory)/$(websitePath)/package-lock.json"
              path: "$(Build.SourcesDirectory)/$(websitePath)/node_modules"

          - script: |
              npm install
            displayName: Install dependencies
            workingDirectory: $(websitePath)
            condition: ne(variables[‘CacheRestored’], ‘true’)

          - script: |
              npm run test:ci
            displayName: Run unit tests
            workingDirectory: $(websitePath)

          # - script: |
          #     ls -la $(Build.SourcesDirectory)/$(websitePath)
          #   displayName: test

          - task: PublishTestResults@2
            displayName: Publish unit test results
            inputs:
              testResultsFormat: "VSTest"
              testResultsFiles: "$(Build.SourcesDirectory)/$(websitePath)/junit.xml"
